spring:
  application:
    name: beCycled-backend
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/becycled
    username: becycled
    password: becycled
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.yandex.ru
    port: 465
    username: no-reply@becycled.me
    password: password
    properties:
      mail.smtp.ssl.enable: true
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 60000
      mail.smtp.writetimeout: 60000

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

mybatis:
  configLocation: classpath:mybatis-config.xml
  checkConfigLocation: true

logging:
  level:
    root: INFO
  file:
    name: logs/all.log
